export const DEFAULT_INCLUDE_DOMAINS: string[] = [
  'bloomberg.com',
  'reuters.com',
  'wsj.com',
  'ft.com',
  'economist.com',
  'nytimes.com',
  'theinformation.com',
  'axios.com',
  'techcrunch.com',
  'theverge.com',
  'arstechnica.com',
  'wired.com',
  'platformer.news',
  'stratechery.com',
  'gartner.com',
  'forrester.com',
  'idc.com',
  '451research.com',
  'cbinsights.com',
  'pitchbook.com',
  'crunchbase.com',
  'businesswire.com',
  'prnewswire.com',
  'news.ycombinator.com',
];

export const DEFAULT_EXCLUDE_DOMAINS: string[] = [
  'finance.yahoo.com',
  'msn.com',
  'news.google.com',
  'smartbrief.com',
  'seekingalpha.com',
  'medium.com',
];
